### ISSUE TITLE
Applikations model GUI

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#22]

**Comment by FrederikKM** [comment]
Har lavet Applikationsmodel til UC 3 og 4

**Comment by Melkfett** [comment]
Applikationsmodeller til UC1 og UC2 lavet

**Comment by hbinderup94** [comment]
Applikationsmodellerne er færdige. 
Ny issue til SPRINT 5: Tilføje funktionskald
