### ISSUE TITLE
Facebook Upload Page Image API (prev. Reverse Engineer Instagram)

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#25]
removed

**Comment by Hestehviskeren** [comment]
Instragram har ssl pinning og signatur key generation, som gør API'en meget svær at reverse engineer.

**Comment by hbinderup94** [comment]
Er blevet udsat til SPRINT 4, da den tager længere tid end forventet

**Comment by Hestehviskeren** [comment]
Mangle problemer med Instragram API ift. sikkerhedsforanstaltninger.
Der påbegyndes en erstatning løsning hvor der benyttes Flickr API (Instragram ligende side)

**Comment by Hestehviskeren** [comment]
Blevet lavet om til FB, vi uploader istedet billeder til en Facebook Side via. Facebook API.

**Comment by Hestehviskeren** [comment]
Virker og testet - brugervenlige funktioner er blevet lavet.
- Mangler noget error-handling, men dette bliver implementeret i UI.
[FB-Page-API.tar.gz](https://github.com/hbinderup94/E17-PROJ3-Gruppe-7/files/1501551/FB-Page-API.tar.gz)
