### ISSUE TITLE
Bygge kamera hardware

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#36]

**Comment by hbinderup94** [comment]
Vi har designet stepper motor boards. De skal testes med motor, og så PCB-printes.

**Comment by DRKobberholm** [comment]
Vi testet kamera hardware, men må konkludere at det er for langsomt. Et nyt design skal derfor bygges

**Comment by hbinderup94** [comment]
Anden issue indeholder samme opgaver
