### ISSUE TITLE
Bygge kassen til #SelfieBooth

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#4]

**Comment by Hestehviskeren** [comment]
Vi samlede kassen så godt vi kunne, og fandt ud af at der mangler et par hjørnebeslag til stabilitet.

**Comment by DRKobberholm** [comment]
Kassen er nu færdigbygget, dog kunne den godt blive stabileseret med et spær eller noget i den stil
