### ISSUE TITLE
WiFi opsætning på server pi og controller pi

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#45]
Skal kunne kommunikere over WiFi

**Comment by simonkroer** [comment]
Da vi har haft et clean install på server pi, har det været bøvlet at få Eduroam WiFi til at fungere.

**Comment by simonkroer** [comment]
Eduroam kan ikke opsættes på et clean Raspbian install, selvom guiden fra cat.eduroam.com følges. Vi prøver at få AU Gadget op at køre.
