### ISSUE TITLE
Open CV med USB Kamera (prev. CSI Kamera)

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#48]
Controller pi skal kunne kommunikere med kameraet via open CV

**Comment by Hestehviskeren** [comment]
Vi har skiftet til et bedre USB kamera, så CSI funtionen er ikke nødvendig - USB kameraet er blevet integreret med openCV(Issue: Designe ansigtsgenkendelse)
