### ISSUE TITLE
Designe ansigtsgenkendelse

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#49]
Skal kunne detektere ansigtet på kamera. Der vil komme en firkant rundt om ansigtet.

**Comment by Hestehviskeren** [comment]
OpenCV test med haarcascades, men der er stadig et stykke vej, bla. problemer med Qt og openCV.

**Comment by Hestehviskeren** [comment]
Alle krav og funktioner er opfyldt(finder ansigt/er og centere fysiske kamera; og live streamer til label og kan tage billeder) - programmmet er blevet integreret med UI.

**Comment by Melkfett** [comment]
Godkendt af gruppe
