### ISSUE TITLE
Ansigtsgenkendelses feedback ift. placering af kamera

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#50]
Skal kunne placere kameratet på COREYXY, så kameraet har ansigtet indenfor 10% af centrum på billedet.

**Comment by hbinderup94** [comment]
Software er skrevet til PSoC. Mangler test med RPI

**Comment by Hestehviskeren** [comment]
Er skrevet (kan sende procenter der mangler for x,y - for at kameraet bliver centeret.
Fysisk test mangles.

**Comment by hbinderup94** [comment]
Software forventes færdigt.
