### ISSUE TITLE
Kommunikation fra GUI til PSoC via I2C 

### ISSUE THREAD

**Issue by hbinderup94** [hbinderup94/E17-PROJ3-Gruppe-7#52]
Skal kunne ændre lys og kamera placering via I2C.

**Comment by Melkfett** [comment]
Mulig løsning fundet. Kode skrevet. Skal testes først før det kan konkluderes.

**Comment by FrederikKM** [comment]
Revideret løsning implementeret, skal testes når vi kan build QT til RPI

**Comment by FrederikKM** [comment]
Kan ikke builde til RPI, issue lukkes
